### PR TITLE
support for browserify with defined window

### PR DESCRIPTION
**Pull request by gugu**

### CODE REVIEW

**Comment by Jxck** [comment]
you can use require() in browserify and build a bundled js including this.

**Comment by gugu** [comment]
no, because window object is defined in this case

**Comment by gugu** [comment]
```
var TextEncoder, TextDecoder;
if (typeof window == 'undefined') {
    ...
}
```

So if window is defined, we have empty variables (TextEncoder === undefined)

**Comment by niftylettuce** [comment]
Yeah this needs fixed.

**Comment by joshgillies** [comment]
has this been released yet?

**Pull request merged**
